import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'screens/lab_screen.dart';
import 'screens/order_screen.dart';
import 'screens/identity_screen.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';


// The Entry Point
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Connect to Firebase using the options generated by 'flutterfire configure'
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // --- THE ERROR HANDLERS ---
  // These are the "nets" that catch bugs and send them to the Firebase console.

  // 1. Catch errors inside the Flutter framework (like build or layout errors)
  FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;

  // 2. Catch asynchronous errors (like network failures or logic bugs outside of widgets)
  PlatformDispatcher.instance.onError = (error, stack) {
    FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    return true;
  };

  runApp(const CrashLabApp());
}

class CrashLabApp extends StatelessWidget {
  const CrashLabApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Crash Lab',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue),
        useMaterial3: true,
      ),
      home: const MainNavigation(),
    );
  }
}

class MainNavigation extends StatefulWidget {
  const MainNavigation({super.key});

  @override
  State<MainNavigation> createState() => _MainNavigationState();
}

class _MainNavigationState extends State<MainNavigation> {
  int _selectedIndex = 0;

  final List<Widget> _screens = [
    const LabScreen(),
    const OrderScreen(),
    const IdentityScreen(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _screens[_selectedIndex],
      bottomNavigationBar: NavigationBar(
        selectedIndex: _selectedIndex,
        onDestinationSelected: (int index) {
          setState(() {
            _selectedIndex = index;
          });
        },
        destinations: const [
          NavigationDestination(icon: Icon(Icons.science), label: 'Lab'),
          NavigationDestination(icon: Icon(Icons.coffee), label: 'Order'),
          NavigationDestination(icon: Icon(Icons.person), label: 'Me'),
        ],
      ),
    );
  }
}
